/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaforce_jni_JFNative */

#ifndef _Included_javaforce_jni_JFNative
#define _Included_javaforce_jni_JFNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIF
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII[F)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII_3F
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JI[I)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JI_3I
  (JNIEnv *, jclass, jlong, jint, jintArray);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JI[II)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JI_3II
  (JNIEnv *, jclass, jlong, jint, jintArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIII
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII[I)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII_3I
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIII[F)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIII_3F
  (JNIEnv *, jclass, jlong, jint, jint, jint, jfloatArray);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIIJ)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIIJ
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlong);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIJJ)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIJJ
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII[FI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII_3FI
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIJ[FI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIJ_3FI
  (JNIEnv *, jclass, jlong, jint, jlong, jfloatArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII[SI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII_3SI
  (JNIEnv *, jclass, jlong, jint, jint, jshortArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIJ[SI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIJ_3SI
  (JNIEnv *, jclass, jlong, jint, jlong, jshortArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII[BI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII_3BI
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIJ[BI)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIJ_3BI
  (JNIEnv *, jclass, jlong, jint, jlong, jbyteArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JII[II)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JII_3II
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIJ[II)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIJ_3II
  (JNIEnv *, jclass, jlong, jint, jlong, jintArray, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIIIII)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIIIIJ
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIIIII[I)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIIIII_3I
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JIIIIIIII[I)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JIIIIIIII_3I
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JZ
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeVoid
 * Signature: (JZZZZ)V
 */
JNIEXPORT void JNICALL Java_javaforce_jni_JFNative_invokeVoid__JZZZZ
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_javaforce_jni_JFNative_invokeInt__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_javaforce_jni_JFNative_invokeInt__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeInt
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_javaforce_jni_JFNative_invokeInt__JIII
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     javaforce_jni_JFNative
 * Method:    invokeLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_javaforce_jni_JFNative_invokeLong
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
